name_mapping = {
    'Deshpande': 'Tushar Deshpande',
    'Mustafizur': 'Mustafizur Rahman',
    'Theekshana': 'Maheesh Theekshana',
    'Chahar': 'Deepak Chahar',
    'Jadeja': 'Ravindra Jadeja',
    'Alzarri': 'Alzarri Joseph',
    'Siraj': 'Mohammed Siraj',
    'Green': 'Cameron Green',
    'Maxwell': 'Glenn Maxwell',
    'Dagar': 'Mayank Dagar',
    'Karn': 'Karn Sharma',
    'Yash': 'Yash Dayal',
    'Karthik': 'Dinesh Karthik',
    'Rawat': 'Anuj Rawat',
    'Kohli': 'Virat Kohli',
    'Patidar': 'Rajat Patidar',
    'du': 'Faf du Plessis',
    'Dube': 'Shivam Dube',
    'Mitchell': 'Daryl Mitchell',
    'Rahane': 'Ajinkya Rahane',
    'Ravindra': 'Rachin Ravindra',
    'Gaikwad': 'Ruturaj Gaikwad',
    'Abishek Porel': 'Abishek Porel',
    'Kuldeep': 'Kuldeep Yadav',
    'Sumit Kumar': 'Sumit Kumar',
    'Axar Patel': 'Axar Patel',
    'Stubbs': 'Tristan Stubbs',
    'Bhui': 'Ricky Bhui',
    'Pant': 'Rishabh Pant',
    'Hope': 'Shai Hope',
    'Warner': 'David Warner',
    'Marsh': 'Mitchell Marsh',
    'Livingstone': 'Liam Livingstone',
    'Harpreet Brar': 'Harpreet Brar',
    'Shashank Singh': 'Shashank Singh',
    'Sam Curran': 'Sam Curran',
    'Sharma': 'Ishant Sharma',
    'Prabhsimran': 'Prabhsimran Singh',
    'S Dhawan': 'Shikhar Dhawan',
    'Bairstow': 'Jonny Bairstow',
    'Harshal': 'Harshal Patel',
    'Arshdeep Singh': 'Arshdeep Singh',
    'Rabada': 'Kagiso Rabada',
    'Chahar': 'Rahul Chahar',
    'Khaleel Ahmed': 'Khaleel Ahmed',
    'Russell': 'Andre Russell',
    'Starc': 'Mitchell Starc',
    'Rinku Singh': 'Rinku Singh',
    'Salt': 'Phil Salt',
    'Ramandeep': 'Ramandeep Singh',
    'Rana': 'Nitish Rana',
    'Shreyas Iyer': 'Shreyas Iyer',
    'Venkatesh Iyer': 'Venkatesh Iyer',
    'Narine': 'Sunil Narine',
    'Cummins': 'Pat Cummins',
    'Klaasen': 'Heinrich Klaasen',
    'Jansen': 'Marco Jansen',
    'Shahbaz Ahmed': 'Shahbaz Ahmed',
    'Abdul Samad': 'Abdul Samad',
    'Tripathi': 'Rahul Tripathi',
    'Markram': 'Aiden Markram',
    'Abhishek': 'Abhishek Sharma',
    'Agarwal': 'Mayank Agarwal',
    'Natarajan': 'T Natarajan',
    'Bhuvneshwar': 'Bhuvneshwar Kumar',
    'Markande': 'Mayank Markande',
    'Harshit Rana': 'Harshit Rana',
    'Varun': 'Varun Chakravarthy',
    'Suyash': 'Suyash Sharma'
}