name_mapping = {
    'Deshpande': 'Tushar Deshpande',
    'Mustafizur': 'Mustafizur Rahman',
    'Theekshana': 'Maheesh Theekshana',
    'Chahar': 'Deepak Chahar',
    'Jadeja': 'Ravindra Jadeja',
    'Alzarri': 'Alzarri Joseph',
    'Siraj': 'Mohammed Siraj',
    'Green': 'Cameron Green',
    'Maxwell': 'Glenn Maxwell',
    'Dagar': 'Mayank Dagar',
    'Karn': 'Karn Sharma',
    'Yash': 'Yash Dayal',
    'Karthik': 'Dinesh Karthik',
    'Rawat': 'Anuj Rawat',
    'Kohli': 'Virat Kohli',
    'Patidar': 'Rajat Patidar',
    'du': 'Faf du Plessis',
    'Dube': 'Shivam Dube',
    'Mitchell': 'Daryl Mitchell',
    'Rahane': 'Ajinkya Rahane',
    'Ravindra': 'Rachin Ravindra',
    'Gaikwad': 'Ruturaj Gaikwad'
}