player_details = {
    'Tushar Deshpande': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm fast-medium', 'Origin': 'Indian'},
    'Mustafizur Rahman': {'batting_side': 'Left-handed', 'bowling_side': 'Left-arm fast-medium', 'Origin': 'Overseas'},
    'Maheesh Theekshana': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm leg-spin', 'Origin': 'Overseas'},
    'Deepak Chahar': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm medium-fast', 'Origin': 'Indian'},
    'Ravindra Jadeja': {'batting_side': 'Left-handed', 'bowling_side': 'Left-arm orthodox', 'Origin': 'Indian'},
    'Alzarri Joseph': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm fast', 'Origin': 'Overseas'},
    'Mohammed Siraj': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm fast-medium', 'Origin': 'Indian'},
    'Cameron Green': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm fast-medium', 'Origin': 'Overseas'},
    'Glenn Maxwell': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm off-spin', 'Origin': 'Overseas'},
    'Mayank Dagar': {'batting_side': 'Left-handed', 'bowling_side': 'Slow left-arm orthodox', 'Origin': 'Indian'},
    'Karn Sharma': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm leg-spin', 'Origin': 'Indian'},
    'Yash Dayal': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm medium', 'Origin': 'Indian'},
    'Dinesh Karthik': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm off-spin', 'Origin': 'Indian'},
    'Anuj Rawat': {'batting_side': 'Right-handed', 'bowling_side': 'None', 'Origin': 'Indian'},
    'Virat Kohli': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm medium', 'Origin': 'Indian'},
    'Rajat Patidar': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm medium', 'Origin': 'Indian'},
    'Faf du Plessis': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm leg-spin', 'Origin': 'Overseas'},
    'Shivam Dube': {'batting_side': 'Left-handed', 'bowling_side': 'Right-arm medium-fast', 'Origin': 'Indian'},
    'Daryl Mitchell': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm medium-fast', 'Origin': 'Overseas'},
    'Ajinkya Rahane': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm medium', 'Origin': 'Indian'},
    'Rachin Ravindra': {'batting_side': 'Left-handed', 'bowling_side': 'Slow left-arm orthodox', 'Origin': 'Overseas'},
    'Ruturaj Gaikwad': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm off-spin', 'Origin': 'Indian'},
    'Abishek Porel': {'batting_side': 'Left-handed', 'bowling_side': 'None', 'Origin': 'Indian'},
    'Kuldeep Yadav': {'batting_side': 'Left-handed', 'bowling_side': 'Left-arm chinaman', 'Origin': 'Indian'},
    'Sumit Kumar': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm medium-fast', 'Origin': 'Indian'},
    'Axar Patel': {'batting_side': 'Left-handed', 'bowling_side': 'Left-arm orthodox', 'Origin': 'Indian'},
    'Tristan Stubbs': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm off-spin', 'Origin': 'Overseas'},
    'Ricky Bhui': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm off-spin', 'Origin': 'Indian'},
    'Rishabh Pant': {'batting_side': 'Left-handed', 'bowling_side': 'None', 'Origin': 'Indian'},
    'Shai Hope': {'batting_side': 'Right-handed', 'bowling_side': 'None', 'Origin': 'Overseas'},
    'David Warner': {'batting_side': 'Left-handed', 'bowling_side': 'None', 'Origin': 'Overseas'},
    'Mitchell Marsh': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm medium-fast', 'Origin': 'Overseas'},
    'Liam Livingstone': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm off-spin', 'Origin': 'Overseas'},
    'Harpreet Brar': {'batting_side': 'Left-handed', 'bowling_side': 'Left-arm orthodox', 'Origin': 'Indian'},
    'Shashank Singh': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm medium', 'Origin': 'Indian'},
    'Sam Curran': {'batting_side': 'Left-handed', 'bowling_side': 'Left-arm fast-medium', 'Origin': 'Overseas'},
    'Ishant Sharma': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm fast-medium', 'Origin': 'Indian'},
    'Prabhsimran Singh': {'batting_side': 'Right-handed', 'bowling_side': 'None', 'Origin': 'Indian'},
    'Shikhar Dhawan': {'batting_side': 'Left-handed', 'bowling_side': 'Right-arm off-spin', 'Origin': 'Indian'},
    'Jonny Bairstow': {'batting_side': 'Right-handed', 'bowling_side': 'None', 'Origin': 'Overseas'},
    'Harshal Patel': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm medium-fast', 'Origin': 'Indian'},
    'Arshdeep Singh': {'batting_side': 'Left-handed', 'bowling_side': 'Left-arm fast-medium', 'Origin': 'Indian'},
    'Kagiso Rabada': {'batting_side': 'Left-handed', 'bowling_side': 'Right-arm fast', 'Origin': 'Overseas'},
    'Rahul Chahar': {'batting_side': 'Right-handed', 'bowling_side': 'Leg-break', 'Origin': 'Indian'},
    'Khaleel Ahmed': {'batting_side': 'Right-handed', 'bowling_side': 'Left-arm medium-fast', 'Origin': 'Indian'},
    'Andre Russell': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm fast-medium', 'origin': 'Overseas'},
    'Harshit Rana': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm fast-medium', 'origin': 'Indian'},
    'T Natarajan': {'batting_side': 'Left-handed', 'bowling_side': 'Left-arm medium-fast', 'origin': 'Indian'},
    'Heinrich Klaasen': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm off-spin', 'origin': 'Overseas'},
    'Sunil Narine': {'batting_side': 'Left-handed', 'bowling_side': 'Right-arm off-spin', 'origin': 'Overseas'},
    'Ramandeep Singh': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm medium', 'origin': 'Indian'},
    'Mayank Markande': {'batting_side': 'Right-handed', 'bowling_side': 'Leg-break', 'origin': 'Indian'},
    'Abhishek Sharma': {'batting_side': 'Left-handed', 'bowling_side': 'Left-arm orthodox', 'origin': 'Indian'},
    'Phil Salt': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm off-spin', 'origin': 'Overseas'},
    'Mayank Agarwal': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm off-spin', 'origin': 'Indian'},
    'Shahbaz Ahmed': {'batting_side': 'Left-handed', 'bowling_side': 'Left-arm orthodox', 'origin': 'Indian'},
    'Pat Cummins': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm fast-medium', 'origin': 'Overseas'},
    'Varun Chakravarthy': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm off-spin', 'origin': 'Indian'},
    'Rinku Singh': {'batting_side': 'Left-handed', 'bowling_side': 'Right-arm off-spin', 'origin': 'Indian'},
    'Suyash Sharma': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm legbreak', 'origin': 'Indian'},
    'Aiden Markram': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm off-spin', 'origin': 'Overseas'},
    'Mitchell Starc': {'batting_side': 'Left-handed', 'bowling_side': 'Left-arm fast', 'origin': 'Overseas'},
    'Venkatesh Iyer': {'batting_side': 'Left-handed', 'bowling_side': 'Right-arm medium', 'origin': 'Indian'},
    'Abdul Samad': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm off-spin', 'origin': 'Indian'},
    'Bhuvneshwar Kumar': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm medium-fast', 'origin': 'Indian'},
    'Shreyas Iyer': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm off-spin', 'origin': 'Indian'},
    'Nitish Rana': {'batting_side': 'Left-handed', 'bowling_side': 'Right-arm off-spin', 'origin': 'Indian'},
    'Rahul Tripathi': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm medium-fast', 'origin': 'Indian'},
    'Marco Jansen': {'batting_side': 'Left-handed', 'bowling_side': 'Left-arm fast-medium', 'origin': 'Overseas'}
}
