player_details = {
    'Tushar Deshpande': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm fast-medium'},
    'Mustafizur Rahman': {'batting_side': 'Left-handed', 'bowling_side': 'Left-arm fast-medium'},
    'Maheesh Theekshana': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm leg-spin'},
    'Deepak Chahar': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm medium-fast'},
    'Ravindra Jadeja': {'batting_side': 'Left-handed', 'bowling_side': 'Left-arm orthodox'},
    'Alzarri Joseph': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm fast'},
    'Mohammed Siraj': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm fast-medium'},
    'Cameron Green': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm fast-medium'},
    'Glenn Maxwell': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm off-spin'},
    'Mayank Dagar': {'batting_side': 'Left-handed', 'bowling_side': 'Slow left-arm orthodox'},
    'Karn Sharma': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm leg-spin'},
    'Yash Dayal': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm medium'},
    'Dinesh Karthik': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm off-spin'},
    'Anuj Rawat': {'batting_side': 'Right-handed', 'bowling_side': 'None'},
    'Virat Kohli': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm medium'},
    'Rajat Patidar': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm medium'},
    'Faf du Plessis': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm leg-spin'},
    'Shivam Dube': {'batting_side': 'Left-handed', 'bowling_side': 'Right-arm medium-fast'},
    'Daryl Mitchell': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm medium-fast'},
    'Ajinkya Rahane': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm medium'},
    'Rachin Ravindra': {'batting_side': 'Left-handed', 'bowling_side': 'Slow left-arm orthodox'},
    'Ruturaj Gaikwad': {'batting_side': 'Right-handed', 'bowling_side': 'Right-arm off-spin'}
}